run:
  concurrency: 8
  deadline: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs:
    - vendor
    - .go

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 15
  govet:
    check-shadowing: false
  goconst:
    min-len: 3
    min-occurrences: 3

linters:
  enable-all: true
  disable:
    - deadcode
    - exhaustivestruct
    - exhaustruct
    - golint
    - gomnd
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - tagliatelle
    - varcheck
    - varnamelen
  fast: false

